"""add_workspace_uniqueness_constraint

Revision ID: 0f59337755c0
Revises: f25500441f36
Create Date: 2026-02-06 18:32:19.671798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f59337755c0'
down_revision: Union[str, None] = 'f25500441f36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_workspace_owner_name', 'workspaces', ['owner_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_workspace_owner_name', 'workspaces', type_='unique')
    # ### end Alembic commands ###
