"""create_categories_table_and_update_budgets

Revision ID: 96677346a08f
Revises: 0f59337755c0
Create Date: 2026-02-06 18:41:57.091847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96677346a08f'
down_revision: Union[str, None] = '0f59337755c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_categories_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_category_workspace_name')
    )
    op.create_index(op.f('ix_categories_workspace_id'), 'categories', ['workspace_id'], unique=False)
    
    # 1. Seed 10 default categories
    import uuid
    from datetime import datetime
    
    categories = [
        ("Vivienda", "Alquiler, hipoteca, servicios del hogar"),
        ("Transporte", "Combustible, transporte público, mantenimiento de vehículos"),
        ("Alimentación", "Supermercado, restaurantes, snacks"),
        ("Servicios", "Electricidad, agua, internet, telefonía"),
        ("Salud y Bienestar", "Gimnasio, seguros, gastos médicos"),
        ("Compras", "Ropa, electrónica, artículos para el hogar"),
        ("Entretenimiento", "Cine, juegos, eventos sociales"),
        ("Educación", "Cursos, libros, colegiaturas"),
        ("Viajes", "Vuelos, hoteles, vacaciones"),
        ("Inversiones", "Acciones, criptomonedas, ahorros"),
    ]
    
    default_cat_ids = []
    for name, desc in categories:
        cat_id = uuid.uuid4()
        default_cat_ids.append(cat_id)
        op.execute(
            sa.text(
                "INSERT INTO categories (id, name, description, is_default, created_at, updated_at) "
                "VALUES (:id, :name, :description, true, now(), now())"
            ).bindparams(id=cat_id, name=name, description=desc)
        )

    # 2. Add category_id to budgets (NULLABLE initially)
    op.add_column('budgets', sa.Column('category_id', sa.UUID(), nullable=True))
    
    # 3. Assign existing budgets to the first category (Housing) or find better match
    # For simplicity, assign to the first one created above
    op.execute(
        sa.text("UPDATE budgets SET category_id = :id").bindparams(id=default_cat_ids[0])
    )
    
    # 4. Now make it non-nullable
    op.alter_column('budgets', 'category_id', nullable=False)

    op.drop_index('ix_budgets_category', table_name='budgets')
    op.drop_constraint('uq_budget_workspace_category_period', 'budgets', type_='unique')
    op.create_unique_constraint('uq_budget_workspace_category_period', 'budgets', ['workspace_id', 'category_id', 'month', 'year'])
    op.create_index(op.f('ix_budgets_category_id'), 'budgets', ['category_id'], unique=False)
    op.create_foreign_key(op.f('fk_budgets_category_id_categories'), 'budgets', 'categories', ['category_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('budgets', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_budgets_category_id_categories'), 'budgets', type_='foreignkey')
    op.drop_index(op.f('ix_budgets_category_id'), table_name='budgets')
    op.drop_constraint('uq_budget_workspace_category_period', 'budgets', type_='unique')
    op.create_unique_constraint('uq_budget_workspace_category_period', 'budgets', ['workspace_id', 'category', 'month', 'year'])
    op.create_index('ix_budgets_category', 'budgets', ['category'], unique=False)
    op.drop_column('budgets', 'category_id')
    op.drop_index(op.f('ix_categories_workspace_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
