"""create_budget_module

Revision ID: f25500441f36
Revises: a8138cd43d8e
Create Date: 2026-02-06 17:45:44.887114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f25500441f36'
down_revision: Union[str, None] = 'a8138cd43d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('limit_amount', sa.Float(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_budgets_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_budgets_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budgets')),
    sa.UniqueConstraint('workspace_id', 'category', 'month', 'year', name='uq_budget_workspace_category_period')
    )
    op.create_index(op.f('ix_budgets_category'), 'budgets', ['category'], unique=False)
    op.create_index(op.f('ix_budgets_owner_id'), 'budgets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_budgets_workspace_id'), 'budgets', ['workspace_id'], unique=False)
    op.drop_constraint('fk_workspace_members_workspace_id_workspaces', 'workspace_members', type_='foreignkey')
    op.create_foreign_key(op.f('fk_workspace_members_workspace_id_workspaces'), 'workspace_members', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    op.drop_constraint('fk_workspaces_owner_id_users', 'workspaces', type_='foreignkey')
    op.create_foreign_key(op.f('fk_workspaces_owner_id_users'), 'workspaces', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_workspaces_owner_id_users'), 'workspaces', type_='foreignkey')
    op.create_foreign_key('fk_workspaces_owner_id_users', 'workspaces', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_constraint(op.f('fk_workspace_members_workspace_id_workspaces'), 'workspace_members', type_='foreignkey')
    op.create_foreign_key('fk_workspace_members_workspace_id_workspaces', 'workspace_members', 'workspaces', ['workspace_id'], ['id'])
    op.drop_index(op.f('ix_budgets_workspace_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_owner_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_category'), table_name='budgets')
    op.drop_table('budgets')
    # ### end Alembic commands ###
